name: Tag Trigger Test

on:
  push:
    tags:
      - "v*"

jobs:
  test-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Show CI context
        run: |
          echo "CI triggered successfully"
          echo "Full ref: $GITHUB_REF"

      - name: Extract tag name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag name is: $TAG_NAME"
